version: '3'

services:
  apache:
    image: php:5.6-apache
    ports:
      - 6091:80
    volumes:
      - "./www:/var/www/html:ro"

  nginx:
    image: nginx
    restart: always
    links:
      - php
    ports:
      - 6092:80
    volumes:
      - "./www:/var/www/html:ro"
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"

  php:
    image: php:5-fpm
    volumes:
      - "./www:/var/www/html:ro"
